/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const DocumentMetadata = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'accessCode' : IDL.Text,
  'mimeType' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadTimestamp' : Time,
  'filename' : IDL.Text,
  'encryptionKey' : IDL.Text,
});
export const FileEventType = IDL.Variant({
  'publicAccess' : IDL.Null,
  'preview' : IDL.Null,
  'delete' : IDL.Null,
  'upload' : IDL.Null,
  'download' : IDL.Null,
});
export const FileEvent = IDL.Record({
  'hash' : IDL.Text,
  'user' : IDL.Principal,
  'fileName' : IDL.Text,
  'fileId' : IDL.Text,
  'timestamp' : Time,
  'eventType' : FileEventType,
});
export const PaymentTransaction = IDL.Record({
  'verified' : IDL.Bool,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkStorageLimit' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'paymentRequired' : IDL.Bool,
          'remainingStorage' : IDL.Nat,
          'canUpload' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'confirmPayment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteDocument' : IDL.Func([IDL.Text], [], []),
  'downloadDocument' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'blob' : ExternalBlob,
            'mimeType' : IDL.Text,
            'filename' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'downloadDocumentWithCode' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'blob' : ExternalBlob,
            'mimeType' : IDL.Text,
            'filename' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentEncryptionKeyWithCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getDocumentMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DocumentMetadata)],
      ['query'],
    ),
  'getDocumentMetadataWithCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DocumentMetadata)],
      ['query'],
    ),
  'getDocumentPreview' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'blob' : ExternalBlob, 'mimeType' : IDL.Text }))],
      ['query'],
    ),
  'getDocumentPreviewWithCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'blob' : ExternalBlob, 'mimeType' : IDL.Text }))],
      ['query'],
    ),
  'getFileHistory' : IDL.Func([], [IDL.Vec(FileEvent)], ['query']),
  'getFileHistoryByFileId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FileEvent)],
      ['query'],
    ),
  'getFileHistoryByType' : IDL.Func(
      [FileEventType],
      [IDL.Vec(FileEvent)],
      ['query'],
    ),
  'getGlobalAnalytics' : IDL.Func(
      [],
      [IDL.Record({ 'totalFiles' : IDL.Nat, 'totalStorage' : IDL.Nat })],
      ['query'],
    ),
  'getPaymentHistory' : IDL.Func([], [IDL.Vec(PaymentTransaction)], ['query']),
  'getUserAnalytics' : IDL.Func(
      [],
      [IDL.Record({ 'userStorage' : IDL.Nat, 'userFiles' : IDL.Nat })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUserDocuments' : IDL.Func([], [IDL.Vec(DocumentMetadata)], ['query']),
  'recordDocumentDownload' : IDL.Func([IDL.Text], [], []),
  'recordDocumentPreview' : IDL.Func([IDL.Text], [], []),
  'recordPublicDownload' : IDL.Func([IDL.Text], [], []),
  'recordPublicPreview' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadDocument' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [IDL.Text],
      [],
    ),
  'validateAccessCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const DocumentMetadata = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'accessCode' : IDL.Text,
    'mimeType' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadTimestamp' : Time,
    'filename' : IDL.Text,
    'encryptionKey' : IDL.Text,
  });
  const FileEventType = IDL.Variant({
    'publicAccess' : IDL.Null,
    'preview' : IDL.Null,
    'delete' : IDL.Null,
    'upload' : IDL.Null,
    'download' : IDL.Null,
  });
  const FileEvent = IDL.Record({
    'hash' : IDL.Text,
    'user' : IDL.Principal,
    'fileName' : IDL.Text,
    'fileId' : IDL.Text,
    'timestamp' : Time,
    'eventType' : FileEventType,
  });
  const PaymentTransaction = IDL.Record({
    'verified' : IDL.Bool,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkStorageLimit' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'paymentRequired' : IDL.Bool,
            'remainingStorage' : IDL.Nat,
            'canUpload' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'confirmPayment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteDocument' : IDL.Func([IDL.Text], [], []),
    'downloadDocument' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'blob' : ExternalBlob,
              'mimeType' : IDL.Text,
              'filename' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'downloadDocumentWithCode' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'blob' : ExternalBlob,
              'mimeType' : IDL.Text,
              'filename' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentEncryptionKeyWithCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getDocumentMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DocumentMetadata)],
        ['query'],
      ),
    'getDocumentMetadataWithCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DocumentMetadata)],
        ['query'],
      ),
    'getDocumentPreview' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'blob' : ExternalBlob, 'mimeType' : IDL.Text }))],
        ['query'],
      ),
    'getDocumentPreviewWithCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'blob' : ExternalBlob, 'mimeType' : IDL.Text }))],
        ['query'],
      ),
    'getFileHistory' : IDL.Func([], [IDL.Vec(FileEvent)], ['query']),
    'getFileHistoryByFileId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FileEvent)],
        ['query'],
      ),
    'getFileHistoryByType' : IDL.Func(
        [FileEventType],
        [IDL.Vec(FileEvent)],
        ['query'],
      ),
    'getGlobalAnalytics' : IDL.Func(
        [],
        [IDL.Record({ 'totalFiles' : IDL.Nat, 'totalStorage' : IDL.Nat })],
        ['query'],
      ),
    'getPaymentHistory' : IDL.Func(
        [],
        [IDL.Vec(PaymentTransaction)],
        ['query'],
      ),
    'getUserAnalytics' : IDL.Func(
        [],
        [IDL.Record({ 'userStorage' : IDL.Nat, 'userFiles' : IDL.Nat })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUserDocuments' : IDL.Func([], [IDL.Vec(DocumentMetadata)], ['query']),
    'recordDocumentDownload' : IDL.Func([IDL.Text], [], []),
    'recordDocumentPreview' : IDL.Func([IDL.Text], [], []),
    'recordPublicDownload' : IDL.Func([IDL.Text], [], []),
    'recordPublicPreview' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadDocument' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [IDL.Text],
        [],
      ),
    'validateAccessCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };