/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DocumentMetadata {
  'id' : string,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'tags' : Array<string>,
  'accessCode' : string,
  'mimeType' : string,
  'folders' : Array<string>,
  'fileSize' : bigint,
  'uploadTimestamp' : Time,
  'filename' : string,
  'encryptionKey' : string,
}
export type ExternalBlob = Uint8Array;
export interface FileEvent {
  'hash' : string,
  'user' : Principal,
  'fileName' : string,
  'fileId' : string,
  'timestamp' : Time,
  'eventType' : FileEventType,
}
export type FileEventType = { 'publicAccess' : null } |
  { 'preview' : null } |
  { 'delete' : null } |
  { 'upload' : null } |
  { 'download' : null } |
  { 'folderTagUpdate' : null };
export interface PaymentTransaction {
  'verified' : boolean,
  'timestamp' : Time,
  'amount' : bigint,
  'transactionId' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkStorageLimit' : ActorMethod<
    [bigint],
    {
      'paymentRequired' : boolean,
      'remainingStorage' : bigint,
      'canUpload' : boolean,
    }
  >,
  'confirmPayment' : ActorMethod<[string, bigint], undefined>,
  'deleteDocument' : ActorMethod<[string], undefined>,
  'downloadDocument' : ActorMethod<
    [string],
    [] | [{ 'blob' : ExternalBlob, 'mimeType' : string, 'filename' : string }]
  >,
  'downloadDocumentWithCode' : ActorMethod<
    [string],
    [] | [{ 'blob' : ExternalBlob, 'mimeType' : string, 'filename' : string }]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocumentEncryptionKeyWithCode' : ActorMethod<[string], [] | [string]>,
  'getDocumentMetadata' : ActorMethod<[string], [] | [DocumentMetadata]>,
  'getDocumentMetadataWithCode' : ActorMethod<
    [string],
    [] | [DocumentMetadata]
  >,
  'getDocumentPreview' : ActorMethod<
    [string],
    [] | [{ 'blob' : ExternalBlob, 'mimeType' : string }]
  >,
  'getDocumentPreviewWithCode' : ActorMethod<
    [string],
    [] | [{ 'blob' : ExternalBlob, 'mimeType' : string }]
  >,
  'getFileHistory' : ActorMethod<[], Array<FileEvent>>,
  'getFileHistoryByFileId' : ActorMethod<[string], Array<FileEvent>>,
  'getFileHistoryByType' : ActorMethod<[FileEventType], Array<FileEvent>>,
  'getGlobalAnalytics' : ActorMethod<
    [],
    { 'totalFiles' : bigint, 'totalStorage' : bigint }
  >,
  'getPaymentHistory' : ActorMethod<[], Array<PaymentTransaction>>,
  'getUserAnalytics' : ActorMethod<
    [],
    { 'userStorage' : bigint, 'userFiles' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUserDocuments' : ActorMethod<[], Array<DocumentMetadata>>,
  'listUserFolders' : ActorMethod<[], Array<string>>,
  'listUserTags' : ActorMethod<[], Array<string>>,
  'recordDocumentDownload' : ActorMethod<[string], undefined>,
  'recordDocumentPreview' : ActorMethod<[string], undefined>,
  'recordPublicDownload' : ActorMethod<[string], undefined>,
  'recordPublicPreview' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDocumentFoldersTags' : ActorMethod<
    [string, Array<string>, Array<string>],
    { 'ok' : DocumentMetadata } |
      { 'err' : string }
  >,
  'uploadDocument' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      ExternalBlob,
      string,
      Array<string>,
      Array<string>,
    ],
    string
  >,
  'validateAccessCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];