/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface FileEvent {
    user: Principal;
    fileName: string;
    fileId: string;
    timestamp: Time;
    eventType: FileEventType;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DocumentMetadata {
    id: string;
    owner: Principal;
    blob: ExternalBlob;
    accessCode: string;
    mimeType: string;
    fileSize: bigint;
    uploadTimestamp: Time;
    filename: string;
    encryptionKey: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaymentTransaction {
    verified: boolean;
    timestamp: Time;
    amount: bigint;
    transactionId: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FileEventType {
    publicAccess = "publicAccess",
    preview = "preview",
    upload = "upload",
    download = "download"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkStorageLimit(fileSize: bigint): Promise<{
        paymentRequired: boolean;
        remainingStorage: bigint;
        canUpload: boolean;
    }>;
    confirmPayment(transactionId: string, amount: bigint): Promise<void>;
    deleteDocument(id: string): Promise<void>;
    downloadDocument(id: string): Promise<{
        blob: ExternalBlob;
        mimeType: string;
        filename: string;
    } | null>;
    downloadDocumentWithCode(code: string): Promise<{
        blob: ExternalBlob;
        mimeType: string;
        filename: string;
    } | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocumentEncryptionKeyWithCode(code: string): Promise<string | null>;
    getDocumentMetadata(id: string): Promise<DocumentMetadata | null>;
    getDocumentMetadataWithCode(code: string): Promise<DocumentMetadata | null>;
    getDocumentPreview(id: string): Promise<{
        blob: ExternalBlob;
        mimeType: string;
    } | null>;
    getDocumentPreviewWithCode(code: string): Promise<{
        blob: ExternalBlob;
        mimeType: string;
    } | null>;
    getFileHistory(): Promise<Array<FileEvent>>;
    getFileHistoryByFileId(fileId: string): Promise<Array<FileEvent>>;
    getFileHistoryByType(eventType: FileEventType): Promise<Array<FileEvent>>;
    getGlobalAnalytics(): Promise<{
        totalFiles: bigint;
        totalStorage: bigint;
    }>;
    getPaymentHistory(): Promise<Array<PaymentTransaction>>;
    getUserAnalytics(): Promise<{
        userStorage: bigint;
        userFiles: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listUserDocuments(): Promise<Array<DocumentMetadata>>;
    recordDocumentDownload(id: string): Promise<void>;
    recordDocumentPreview(id: string): Promise<void>;
    recordPublicDownload(code: string): Promise<void>;
    recordPublicPreview(code: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    uploadDocument(filename: string, fileSize: bigint, accessCode: string, encryptionKey: string, blob: ExternalBlob, mimeType: string): Promise<string>;
    validateAccessCode(code: string): Promise<boolean>;
}
import type { DocumentMetadata as _DocumentMetadata, ExternalBlob as _ExternalBlob, FileEvent as _FileEvent, FileEventType as _FileEventType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async checkStorageLimit(arg0: bigint): Promise<{
        paymentRequired: boolean;
        remainingStorage: bigint;
        canUpload: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkStorageLimit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkStorageLimit(arg0);
            return result;
        }
    }
    async confirmPayment(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0, arg1);
            return result;
        }
    }
    async deleteDocument(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async downloadDocument(arg0: string): Promise<{
        blob: ExternalBlob;
        mimeType: string;
        filename: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadDocument(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadDocument(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async downloadDocumentWithCode(arg0: string): Promise<{
        blob: ExternalBlob;
        mimeType: string;
        filename: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadDocumentWithCode(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadDocumentWithCode(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDocumentEncryptionKeyWithCode(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentEncryptionKeyWithCode(arg0);
                return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentEncryptionKeyWithCode(arg0);
            return from_candid_opt_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDocumentMetadata(arg0: string): Promise<DocumentMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentMetadata(arg0);
                return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentMetadata(arg0);
            return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDocumentMetadataWithCode(arg0: string): Promise<DocumentMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentMetadataWithCode(arg0);
                return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentMetadataWithCode(arg0);
            return from_candid_opt_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDocumentPreview(arg0: string): Promise<{
        blob: ExternalBlob;
        mimeType: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentPreview(arg0);
                return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentPreview(arg0);
            return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDocumentPreviewWithCode(arg0: string): Promise<{
        blob: ExternalBlob;
        mimeType: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentPreviewWithCode(arg0);
                return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentPreviewWithCode(arg0);
            return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileHistory(): Promise<Array<FileEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileHistory();
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileHistory();
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileHistoryByFileId(arg0: string): Promise<Array<FileEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileHistoryByFileId(arg0);
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileHistoryByFileId(arg0);
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFileHistoryByType(arg0: FileEventType): Promise<Array<FileEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileHistoryByType(to_candid_FileEventType_n27(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileHistoryByType(to_candid_FileEventType_n27(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGlobalAnalytics(): Promise<{
        totalFiles: bigint;
        totalStorage: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalAnalytics();
            return result;
        }
    }
    async getPaymentHistory(): Promise<Array<PaymentTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentHistory();
            return result;
        }
    }
    async getUserAnalytics(): Promise<{
        userStorage: bigint;
        userFiles: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAnalytics();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listUserDocuments(): Promise<Array<DocumentMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserDocuments();
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserDocuments();
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async recordDocumentDownload(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDocumentDownload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDocumentDownload(arg0);
            return result;
        }
    }
    async recordDocumentPreview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDocumentPreview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDocumentPreview(arg0);
            return result;
        }
    }
    async recordPublicDownload(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPublicDownload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPublicDownload(arg0);
            return result;
        }
    }
    async recordPublicPreview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPublicPreview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPublicPreview(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async uploadDocument(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: ExternalBlob, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n30(this.uploadFile, this.downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n30(this.uploadFile, this.downloadFile, arg4), arg5);
            return result;
        }
    }
    async validateAccessCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAccessCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAccessCode(arg0);
            return result;
        }
    }
}
async function from_candid_DocumentMetadata_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentMetadata): Promise<DocumentMetadata> {
    return await from_candid_record_n19(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
function from_candid_FileEventType_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileEventType): FileEventType {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid_FileEvent_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileEvent): FileEvent {
    return from_candid_record_n24(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
async function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        blob: _ExternalBlob;
        mimeType: string;
        filename: string;
    }]): Promise<{
    blob: ExternalBlob;
    mimeType: string;
    filename: string;
} | null> {
    return value.length === 0 ? null : await from_candid_record_n11(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentMetadata]): Promise<DocumentMetadata | null> {
    return value.length === 0 ? null : await from_candid_DocumentMetadata_n18(uploadFile, downloadFile, value[0]);
}
async function from_candid_opt_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        blob: _ExternalBlob;
        mimeType: string;
    }]): Promise<{
    blob: ExternalBlob;
    mimeType: string;
} | null> {
    return value.length === 0 ? null : await from_candid_record_n21(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    mimeType: string;
    filename: string;
}): Promise<{
    blob: ExternalBlob;
    mimeType: string;
    filename: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n12(uploadFile, downloadFile, value.blob),
        mimeType: value.mimeType,
        filename: value.filename
    };
}
async function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    blob: _ExternalBlob;
    accessCode: string;
    mimeType: string;
    fileSize: bigint;
    uploadTimestamp: _Time;
    filename: string;
    encryptionKey: string;
}): Promise<{
    id: string;
    owner: Principal;
    blob: ExternalBlob;
    accessCode: string;
    mimeType: string;
    fileSize: bigint;
    uploadTimestamp: Time;
    filename: string;
    encryptionKey: string;
}> {
    return {
        id: value.id,
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n12(uploadFile, downloadFile, value.blob),
        accessCode: value.accessCode,
        mimeType: value.mimeType,
        fileSize: value.fileSize,
        uploadTimestamp: value.uploadTimestamp,
        filename: value.filename,
        encryptionKey: value.encryptionKey
    };
}
async function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    mimeType: string;
}): Promise<{
    blob: ExternalBlob;
    mimeType: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n12(uploadFile, downloadFile, value.blob),
        mimeType: value.mimeType
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    fileName: string;
    fileId: string;
    timestamp: _Time;
    eventType: _FileEventType;
}): {
    user: Principal;
    fileName: string;
    fileId: string;
    timestamp: Time;
    eventType: FileEventType;
} {
    return {
        user: value.user,
        fileName: value.fileName,
        fileId: value.fileId,
        timestamp: value.timestamp,
        eventType: from_candid_FileEventType_n25(uploadFile, downloadFile, value.eventType)
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    publicAccess: null;
} | {
    preview: null;
} | {
    upload: null;
} | {
    download: null;
}): FileEventType {
    return "publicAccess" in value ? FileEventType.publicAccess : "preview" in value ? FileEventType.preview : "upload" in value ? FileEventType.upload : "download" in value ? FileEventType.download : value;
}
function from_candid_vec_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileEvent>): Array<FileEvent> {
    return value.map((x)=>from_candid_FileEvent_n23(uploadFile, downloadFile, x));
}
async function from_candid_vec_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentMetadata>): Promise<Array<DocumentMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DocumentMetadata_n18(uploadFile, downloadFile, x)));
}
async function to_candid_ExternalBlob_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_FileEventType_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileEventType): _FileEventType {
    return to_candid_variant_n28(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileEventType): {
    publicAccess: null;
} | {
    preview: null;
} | {
    upload: null;
} | {
    download: null;
} {
    return value == FileEventType.publicAccess ? {
        publicAccess: null
    } : value == FileEventType.preview ? {
        preview: null
    } : value == FileEventType.upload ? {
        upload: null
    } : value == FileEventType.download ? {
        download: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
